### ISSUE TITLE
.jar is named jigawatt

### ISSUE THREAD

**Issue by judovana** [chflood/jigawatts#16]
Both pom and configure reffers final jar as jigawatt.jar Maybe it shoudl be jigawatts.jar? This is not an issue, just verifying. Project is jigawatts, library is  libJigawatts.so....

**Comment by judovana** [comment]
Once we release for rhel, the name will be sealed

**Comment by gnu-andrew** [comment]
Yeah, I noticed this too. I'll post the patch I have to fix it.

**Comment by judovana** [comment]
fixed. It is now jigawatts.jar
